 import Foundation
import UIKit

enum DefaultStorageLocation: String {
    case refrigerator
    case freezer
    case pantry
    case changeMe
}
//let newArrayOfFoods: KeyValuePairs = ["oranges":"🍊", "eggs":"🥚", "bread":"🍞", "cake":"🎂", "watermelon":"🍉", "grapes":"🍇", "chicken wings":"🍗", "mug cake":"🧁", "cup cake":"🧁", "pizza":"🍕", "hot dog":"🌭", "caviar":"🐟", "parmesean":"🧀", "cheese":"🧀", "bbq":"🍖", "pork":"🐖", "eggs":"🥚", "milk":"🥛", "soy milk":"🥛", "creme caremal":"🍮", "brocolie":"🥦", "onion":"🧅", "donut":"🍩", "cherries":"🍒", "green apple":"🍏", "banana":"🍌", "carrot":"🥕", "pumpkin pie":"🥧", "pastrys":"🥐", "cokkies":"🍪", "mandarine":"🍊", "spinach":"🥬", "bok choi":"🥬", "ramen":"🍜", "noodles":"🍜", "chipotle":"🥙", "taco":"🌮", "burrito":"🌯", "sugar":"🍬", "mango":"🥭", "asparagus":"🌲", "acorn squash":"🌰", "almond":"🌰", "apple saurce":"🍎", "asian noodles":"🍜", "cantaloupe":"🍈", "tuna":"🐟", "apple juice":"🧃", "avocado roll":"🥑", "bacon":"🥓", "black beans":"🌰", "bagels":"🥐", "baked beans":"🌰", "beer":"🍺", "fish":"🐠", "cabbage":"🥬", "celery":"🥬", "cat fish":"🐟", "chips":"🍟", "chocolate":"🍫", "chowder":"🍲", "clams":"🦪", "coffee":"☕️", "corn":"🌽", "crab":"🦀", "curry":"🍛", "cereal":"🥣", "kimchi":"🇰🇷", "dates":"🌰", "dips":"🥣", "duck":"🦆", "dumplings":"🥟", "donuts":"🍩", "enchilada":"🥘", "eggrolls":"🍳", "english muffins":"🧁", "muffins":"🧁", "edimame":"🥬", "sushi":"🍣", "fondue":"🧀", "french toast":"🍞", "garlic":"🧄", "ginger":"🥕", "gnochhi":"🍝", "goose":"🦆", "granola":"🍫", "green beans":"🌰", "beans":"🌰", "guacamole":"🥑", "grahm crackers":"🍘", "ham":"🐖", "hamburger":"🍔", "honey":"🍯", "hashbrowns":"🍟", "hikurolls":"🥞", "hummus":"🥫", "irish stew":"🍲", "indian food":"🇮🇳", "italian bread":"🥖", "jam":"🥫", "jelly":"🥫", "jerky":"🥓", "jalapeno":"🌶", "kale":"🥬", "ketchup":"🥫", "kiwi":"🥝", "kingfish":"🐠", "lobster":"🦞", "lamb":"🐑", "lasagna":"🍝", "meatballs":"🍖", "moose":"🦌", "milkshake":"🥤", "peperoni":"🍕", "panckaes":"🥞", "quesadila":"🌮", "spaghetti":"🍝", "tatter tots":"🍟", "toast":"🍞", "udon noodles":"🍜", "udon":"🍜", "venison":"🥩","waffles":"🧇", "wasabi":"🍣", "wine":"🍷", "walnuts":"🌰", "yogurt":"🥛", "ziti":"🍝", "zucchini":"🥒", "ugli":"🍊", "tangerine":"🍊","oatmeal":"🥣", "goat cheese":"🧀", "mushrooms":"🍄", "pears":"🍐", "raspberry":"🍇", "strawberry":"🍓", "fig":"🥭", "passion fruit":"🍊", "pineuts":"🌰", "cherries":"🍒", "olives":"🍐", "cottage cheese":"🧀", "tuna":"🐟", "refried beans":"🌰", "bell peppers":"🌶", "salmon":"🐠", "pineapple":"🍍", "sweet potatoes":"🍠", "rice cake":"🍙", "mochi":"🍡", "pinto beans":"🌰", "coconut":"🥥", "purple yam":"🍠", "urchins":"🐡", "ukraine rolls":"🥞", "umbrella fruit":"🍐", "papaya":"🥭", "steak":"🥩", "extreme candy":"🍬", "hot sauce":"🌶", "xo sauce":"🥫", "shrimp":"🦐", "parsley":"🥬", "sausage":"🥓", "tomato":"🍅", "tapioca pearls":"⚫️", "tortillas":"🌮", "vanilla":"🍨", "fries":"🍟", "mushroom":"🍄", "radish":"🥕", "yam":"🍠", "oranges":"🍊", "potato":"🥔", "orange":"🍊", "blueberries":"🍇", "blackberries":"🍇", "brandy":"🍺", "butter":"🧈", "pork":"🐖", "beets":"🥕", "cider":"🍺", "cauliflower":"🥦", "clam":"🐚", "cranberries":"🍇", "dressing":"🥫", "doritos":"🍟", "cheetos":"🍟", "takis":"🍟", "french fries":"🍟", "juice":"🧃", "lettuce":"🥬", "mayonnaise":"🥫", "mozzarella":"🧀", "macaroon":"🍜", "mustard":"🥫", "meatloaf":"🍖", "popcorn":"🍿", "peppers":"🌶", "peaches":"🍑", "pretzels":"🥨", "popsicle":"🧊", "pomegranate":"🍎", "quail egg":"🥚", "rum":"🍺", "raisins":"🍇", "ravioli":"🥟", "salmon":"🐟", "sandwich":"🥪", "turkey":"🦃", "left overs":"🍲", "frosting":"🧁", "fudge":"🍫", "flour":"🌾", "gravy":"🍲", "grapefruit":"🍊", "ground beef":"🥩", "hazelnut":"🌰", "burgers":"🍔", "meatballs":"🍖", "noodles":"🍜", "turnip":"🍠", "pasta":"🍝", "appracot":"🍑", "breadfruit":"🍐", "buckwheat":"🌾", "cucumber":"🥒", "lemons":"🍋", "red velvet cake":"🍰", "star fruit":"🍋", "dragon fruit":"🍎", "peanut butter":"🥜", "oreo pie":"🥧", "cheese cake":"🧀", "brownies":"🍫", "sauce":"🥫", "pickles":"🥒", "peas":"🌰", "rice":"🍚", "chinese food":"🇨🇳", "japanese food":"🇯🇵", "beef stew":"🍲", "chicken soup":"🐣", "chicken noodle soup":"🍜", "sweet potatoes":"🍠", "dandelion":"🌼", "grape":"🍇", "brussel sprouts":"🥬", "corn salad":"🥗", "dill":"🥬", "lettuce":"🥬", "sea beet":"🥬", "sea kale":"🥬", "water grass":"🥬", "wheatgrass":"🌾", "bittermelon":"🍈", "eggplant":"🍆", "olive fruit":"🍐", "pumpkin":"🎃", "sweet pepper":"🌶", "winter melon":"🍈", "chickpeas":"🌰", "common peas":"🌰", "indian pea":"🌰", "peanut":"🥜", "soybean":"🌰", "chives":"🥬", "garlic chives":"🥬", "lemon grass":"🥬", "leek":"🥬", "lotus root":"🥥", "pearl onion":"🧅", "spring onion":"🧅", "green onion":"🧅", "mondrian wild rice":"🍚", "bamboo shoot":"🎍", "beetroot":"🥕", "canna":"🌼", "cassava":"🥕", "horseradish":"🥕", "parsnip":"🥕", "tea":"🍵", "tigernut":"🌰", "sea lettuce":"🥬", "biscuit":"🍪", "meat":"🥩", "hot pot":"🍲", "pork chop":"🐖", "panna cotta":"🍮", "pancake mix":"🥞", "wontons":"🥟", "frozen dumplings":"🥟", "dumplings":"🥟", "sourdough":"🌾", "sourdough bread":"🍞", "graham cracker":"🍪", "macaroni":"🍝", "macaroni and cheese":"🍝", "chicken alfredo":"🍝", "mochi ice cream":"🍦", "pineapple":"🍍", "pineapple cake":"🍰", "banana bread":"🍞", "blueberry muffins":"🧁", "aloe juice":"🥤", "aloe vera drink":"🥤", "smoothie":"🥤", "macaroon":"🍬", "marinara sauce":"🥫", "mini potatoes":"🥔", "honeycrisp apples":"🍎", "japanese pumpkin":"🎃", "basil":"🥬", "frozen mango":"🥭", "dried mango":"🥭", "beef jerky":"🥓", "tangerines":"🍊", "clementimes":"🍊", "sugar canes":"🍬", "honeydew":"🍈", "asian pears":"🍐", "congee":"🍚", "yellow onions":"🧅", "baby carrots":"🥕", "grape tomatoes":"🍅", "white mushrooms":"🍄", "sweet onions":"🧅", "romanine lettuce":"🥬", "sweet corn cobs":"🌽", "corn":"🌽", "shallot":"🧅", "brocolie florets":"🥦", "golden potatos":"🥔", "russet potatoes":"🥔", "chayote squash":"🍈", "peeled garlic":"🧄", "spaghetti squash":"🍝", "boston lettuce":"🥬", "diced yellow onions":"🧅", "butternut sqaush":"🍟", "curly mustard":"🥬", "lime":"🍋", "lemons":"🍋", "seedless grapes":"🍇", "red mango":"🥭", "seedless watermelon":"🍉", "navel oranges":"🍊", "granny smith apples":"🍏", "gala apples":"🍎", "seeded red watermelon":"🍉", "barlett pear":"🍐", "bosc pear":"🍐", "sungold kiwi":"🥝", "honeydew melon":"🍈", "lunchables":"🍱", "ground beef":"🍖", "ground pork":"🐖", "smoked bacon":"🥓", "cracker crunchers":"🍪", "nachos":"🇲🇽", "chicken drumsticks":"🍗", "mashed potatos":"🥔", "ground turkey":"🦃", "italian sausage":"🌭", "chinese sausage":"🌭", "sausage":"🌭", "shrimp":"🦐", "frozen shrimp":"🦐", "tuna":"🐟", "frito-lay":"🍟", "tortilla chips":"🍟", "hot dog buns":"🌭", "ramen noodle soup":"🍜", "potato chips":"🍟", "ritz stacks original crackers":"🍪", "barbecue sauce":"🥫", "toasted coconut chips":"🍟", "coconut":"🥥", "white sliced bread":"🍞", "canned green beans":"🥫", "oreos":"🍪", "taco seasoning":"🌮", "flaming hot cheetos":"🍟", "diced tomatos":"🍅", "chili":"🌶", "beef ravioli":"🥟", "bruger buns":"🍔", "honey maid grahm crackers":"🍪", "cheez it":"🍟", "cream of chicken soup":"🍲", "pringles":"🍟", "penne pasta":"🍝", "bbq potato chips":"🍟", "ranch":"🥫", "tomato paste":"🍅", "chicken broth":"🍲", "vegetable broth":"🍲", "fat free skim milk":"🥛", "chocolate milk":"🥛", "sharp cheddar cheese":"🧀", "cheddar":"🧀", "yogurt":"🥛", "greek yogurt":"🥛", "pasteurized milk":"🥛", "egg whites":"🥚", "mexican style blend":"🇲🇽", "american cheese":"🧀", "coffemate":"☕️", "coffee creamer":"☕️", "sour cream":"🥛", "unsalted butter":"🧈", "salted butter":"🧈", "wipped cream":"", "cream cheese":"", "heavy cream":"", "cinnamon rolls":"🍬", "chobani greek yogurt":"🥛", "almond milk":"🥛", "soy milk":"🥛", "oat milk":"🥛", "buttermilk biscuits":"🍪", "macaroni salad":"🥗", "mustard potato salad":"🥗", "chicken teneders":"🍗", "fresh mozerella":"🧀", "feta cheese":"🧀", "pretzel":"🥨", "dinner rolls":"🍞", "crossants":"🥐", "mini crossants":"🥐", "savory butter rolls":"🧈", "chocolate chip cookies":"🍪", "m&m cookies":"🍬", "flat bread":"🍞", "desert shells":"🐚", "mini donuts":"🍩", "apple pie":"🥧", "garlic naan flatbread":"🍞", "brownies":"🍫", "bakery fresh goodness mini cinnamon rolls":"🍬", "sugar cookies":"🍪", "reese's peanut butter cups":"🥜", "kitkat":"🍫", "m&ms":"🍬", "spinach":"🥬", "cappuccino":"☕️", "bacon":"🥓", "sunnyside up":"🍳", "cinnamon":"🍬", "juice":"🧃"]

var newerArrayOfFoods =  [
                         ["name": "eggs", "emoji": "🥚", "lastsFor": 28, "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["name": "bread", "emoji": "🍞", "lastsFor": 5, "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["emoji": "🎂", "lastsFor": 3, "name": "cake", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["lastsFor": 3, "name": "watermelon", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🍉"],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 7, "emoji": "🍇", "name": "grapes"],
                         ["emoji": "🍗", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 4, "name": "chicken wings"],
                         ["emoji": "🧁", "name": "cup cake", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 7],
                         ["name": "pizza", "emoji": "🍕", "lastsFor": 3, "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 7, "name": "hot dog", "emoji": "🌭"],
                         ["lastsFor": 12, "emoji": "🐟", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "caviar"],
                         ["name": "parmesean", "emoji": "🧀", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 42],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 42, "emoji": "🧀", "name": "cheese"],
                         ["lastsFor": 3, "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "bbq", "emoji": "🍖"],
                         ["lastsFor": 2, "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "pork", "emoji": "🐖"],
                         ["defaultSL": DefaultStorageLocation.refrigeragtor.rawValue, "lastsFor": 6, "emoji": "🥛", "name": "milk"],
                         ["name": "soy milk", "emoji": "🥛", "defaultSL": DefaultStorageLocation.refrigeraotr.rawValue, "lastsFor": 6],
                         ["name": "creme caremal", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🍮", "lastsFor": 2],
                         ["emoji": "🥦", "lastsFor": 6, "name": "brocolie", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "onion", "emoji": "🧅", "lastsFor": 8],
                         ["lastsFor": 7, "name": "donut", "emoji": "🍩", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["name": "cherries", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 7, "emoji": "🍒"],
                         ["defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 6, "name": "green apple", "emoji": "🍏"],
                         ["emoji": "🍌", "name": "banana", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 4],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 14, "name": "carrot", "emoji": "🥕"],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🥧", "lastsFor": 3, "name": "pumpkin pie"],
                         ["name": "pastries", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 2, "emoji": "🥐"],
                         ["defaultSL": DefaultStorageLocation.pantry.rawValue, "name": "cookies", "emoji": "🍪", "lastsFor": 14],
                         ["lastsFor": 10, "emoji": "🍊", "name": "mandarine", "defaultSL": DefaultStorageLocation.pantry.rawValue],
                         ["name": "spinach", "emoji": "🥬", "lastsFor": 14, "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 4, "emoji": "🥬", "name": "bok choy"],
                         ["defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🍜", "name": "ramen", "lastsFor": 365],
                         ["defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🍜", "lastsFor": 180, "name": "noodles"],
                         ["emoji": "🥙", "name": "chipotle", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 3],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 3, "name": "taco", "emoji": "🌮"],
                         ["name": "burrito", "emoji": "🌯", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 3],
                         ["name": "sugar", "emoji": "🍬", "lastsFor": 730, "defaultSL": DefaultStorageLocation.pantry.rawValue],
                         ["lastsFor": 5, "emoji": "🥭", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "mango"],
                         ["name": "asparagus", "lastsFor": 7, "emoji": "🌲", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["emoji": "🌰", "name": "acorn squash", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 14],
                         ["name": "almond", "lastsFor": 730, "defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🌰"],

                         ["emoji": "🍎", "name": "apple saurce", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 14],
                         ["emoji": "🍜", "name": "asian noodles", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 730],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 8, "name": "cantaloupe", "emoji": "🍈"],
                         ["name": "tuna", "lastsFor": 3, "emoji": "🐟", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["lastsFor": 75, "name": "apple juice", "emoji": "🧃", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["name": "avocado roll", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🥑", "lastsFor": 3],
                         ["name": "bacon", "lastsFor": 14, "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🥓"],
                         ["name": "black beans", "emoji": "🌰", "lastsFor": 1105, "defaultSL": DefaultStorageLocation.pantry.rawValue],
                         ["name": "bagels", "emoji": "🥐", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 5],
                         ["name": "baked beans", "emoji": "🌰", "lastsFor": 3, "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["defaultSL": DefaultStorageLocation.pantry.rawValue, "name": "beer", "lastsFor": 210, "emoji": "🍺"],
                         ["emoji": "🐠", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "fish", "lastsFor": 3],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "cabbage", "emoji": "🥬", "lastsFor": 40],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "celery", "emoji": "🥬", "lastsFor": 24],
                         ["lastsFor": 3, "name": "cat fish", "emoji": "🐟", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["name": "chips", "emoji": "🍟", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 75],
                         ["defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🍫", "name": "chocolate", "lastsFor": 365],
                         ["name": "chowder", "lastsFor": 3, "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🍲"],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "clams", "lastsFor": 2, "emoji": "🦪"],
                         ["name": "coffee", "lastsFor": 3, "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "☕️"],
                         ["lastsFor": 2, "name": "corn", "emoji": "🌽", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["name": "crab", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 2, "emoji": "🦀"],
                         ["lastsFor": 90, "name": "curry", "emoji": "🍛", "defaultSL": DefaultStorageLocation.pantry.rawValue],
                         ["defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 90, "emoji": "🥣", "name": "cereal"],
                         ["lastsFor": 135, "name": "kimchi", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🇰🇷"],
                         ["name": "dates", "lastsFor": 270, "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🌰"],
                         ["emoji": "🥣", "lastsFor": 7, "name": "dips", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["name": "duck", "emoji": "🦆", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 8],
                         ["defaultSL": DefaultStorageLocation.freezer.rawValue, "name": "dumplings", "lastsFor": 90, "emoji": "🥟"],
                         ["emoji": "🍩", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 7, "name": "donuts"],
                         ["lastsFor": 4, "name": "enchilada", "emoji": "🥘", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["emoji": "🍳", "lastsFor": 3, "name": "eggrolls", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["lastsFor": 14, "defaultSL": DefaultStorageLocation.pantry.rawValue, "name": "english muffins", "emoji": "🧁"],
                         ["lastsFor": 7, "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "muffins", "emoji": "🧁"],
                         ["name": "edamame", "lastsFor": 365, "defaultSL": DefaultStorageLocation.freezer.rawValue, "emoji": "🥬"],
                         ["emoji": "🍣", "lastsFor": 3, "name": "sushi", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["emoji": "🧀", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 42, "name": "fondue"],
                         ["emoji": "🍞", "name": "french toast", "defaultSL": DefaultStorageLocation.freezer.rawValue, "lastsFor": 90],
                         ["name": "garlic", "emoji": "🧄", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 21],
                         ["lastsFor": 14, "name": "ginger", "emoji": "🥕", "defaultSL": DefaultStorageLocation.refrigerator.rawValue],
                         ["name": "gnochhi", "emoji": "🍝", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 30],
                         ["emoji": "🦆", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "goose", "lastsFor": 8],
                         ["lastsFor": 180, "emoji": "🍫", "defaultSL": DefaultStorageLocation.pantry.rawValue, "name": "granola"],
                         ["lastsFor": 7, "name": "green beans", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🌰"],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🌰", "lastsFor": 4, "name": "beans"],
                         ["name": "guacamole", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🥑", "lastsFor": 2],
                         ["defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🍘", "lastsFor": 210, "name": "grahm crackers"],
                         ["emoji": "🐖", "name": "ham", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 5],
                         ["name": "hamburger", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🍔", "lastsFor": 2],
                         ["emoji": "🍯", "name": "honey", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 99999],
                         ["lastsFor": 365, "emoji": "🍟", "name": "hashbrowns", "defaultSL": DefaultStorageLocation.freezer.rawValue],
                         ["emoji": "🥫", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 7, "name": "hummus"],
                         ["emoji": "🍲", "name": "irish stew", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 3],
                         ["lastsFor": 4, "name": "indian food", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🇮🇳"],
                         ["defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🥖", "name": "italian bread", "lastsFor": 3],
                         ["emoji": "🥫", "name": "jam", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 365],
                         ["emoji": "🥫", "lastsFor": 270, "name": "jelly", "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 

                         ["lastsFor": 730, "name": "jerky", "emoji": "🥓", "defaultSL": DefaultStorageLocation.pantry.rawValue], 
                         ["name": "jalapeno", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🌶", "lastsFor": 3],
                         ["lastsFor": 6, "emoji": "🥬", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "kale"],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "ketchup", "emoji": "🥫", "lastsFor": 180], 
                         ["name": "kiwi", "emoji": "🥝", "lastsFor": 28, "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 3, "emoji": "🐠", "name": "kingfish"],
                         ["name": "lobster", "emoji": "🦞", "lastsFor": 4, "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["emoji": "🐑", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "lamb", "lastsFor": 5], 
                         ["name": "lasagna", "emoji": "🍝", "lastsFor": 210, "defaultSL": DefaultStorageLocation.freezer.rawValue], 
                         ["defaultSL": DefaultStorageLocation.freezer.rawValue, "emoji": "🍖", "name": "meatballs", "lastsFor": 90],
                         ["lastsFor": 2, "emoji": "🥤", "name": "milkshake", "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 21, "name": "peperoni", "emoji": "🍕"],
                         ["name": "panckaes", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 3, "emoji": "🥞"], 
                         ["name": "2", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🌮", "lastsFor": 9999999],
                         ["emoji": "🍝", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 4, "name": "spaghetti"],
                         ["name": "tatter tots", "emoji": "🍟", "lastsFor": 270, "defaultSL": DefaultStorageLocation.freezer.rawValue],
                         ["lastsFor": 7, "emoji": "🍞", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "toast"], 
                         ["emoji": "🍜", "lastsFor": 365, "name": "udon noodles", "defaultSL": DefaultStorageLocation.pantry.rawValue],
                         ["lastsFor": 365, "name": "udon", "defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🍜"],
                         ["defaultSL": DefaultStorageLocation.freezer.rawValue, "lastsFor": 270, "name": "venison", "emoji": "🥩"],
                         ["lastsFor": 365, "emoji": "🍣", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "wasabi"], 
                         ["defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 1095, "emoji": "🍷", "name": "wine"],
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🌰", "name": "walnuts", "lastsFor": 180], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 14, "name": "yogurt", "emoji": "🥛"],
                         ["lastsFor": 60, "defaultSL": DefaultStorageLocation.freezer.rawValue, "name": "ziti", "emoji": "🍝"],
                         ["emoji": "🥒", "name": "zucchini", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 5],
                         ["name": "ugli", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🍊", "lastsFor": 4], 
                         ["lastsFor": 10, "emoji": "🍊", "defaultSL": DefaultStorageLocation.pantry.rawValue, "name": "tangerine"],
                         ["name": "oatmeal", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 550, "emoji": "🥣"],
                         ["name": "goat cheese", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 21, "emoji": "🧀"],
                         ["name": "mushrooms", "lastsFor": 10, "emoji": "🍄", "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 5, "name": "pears", "emoji": "🍐"],
                         ["emoji": "🍇", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 5, "name": "raspberry"],
                         ["name": "strawberry", "lastsFor": 7, "emoji": "🍓", "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🥭", "name": "fig", "lastsFor": 3],
                         ["emoji": "🍊", "name": "passion fruit", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 14], 
                         ["emoji": "🌰", "defaultSL": DefaultStorageLocation.pantry.rawValue, "name": "pineuts", "lastsFor": 60], 
                         ["emoji": "🍒", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 7, "name": "cherries"], 
                         ["emoji": "🍐", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 120, "name": "olives"],
                         ["lastsFor": 14, "name": "cottage cheese", "emoji": "🧀", "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["lastsFor": 3, "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "tuna", "emoji": "🐟"], 
                         ["emoji": "🌰", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 4, "name": "refried beans"], 
                         ["name": "bell peppers", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 14, "emoji": "🌶"], 
                         ["emoji": "🐠", "name": "salmon", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 2], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 5, "emoji": "🍍", "name": "pineapple"], 
                         ["name": "sweet potatoes", "emoji": "🍠", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 14], 
                         ["emoji": "🍙", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 21, "name": "rice cake"], 
                         ["name": "mochi", "emoji": "🍡", "lastsFor": 14, "defaultSL": DefaultStorageLocation.freezer.rawValue],

                         ["name": "pinto beans", "defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🌰", "lastsFor": 720], 
                         ["name": "coconut", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 14, "emoji": "🥥"], 
                         ["emoji": "🍠", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 21, "name": "purple yam"],
                         ["name": "urchins", "emoji": "🐡", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 2], 
                         ["emoji": "🍐", "name": "umbrella fruit", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 7], 
                         ["defaultSL": DefaultStorageLocation.refrifgerator.rawValue, "lastsFor": 7, "name": "papaya", "emoji": "🥭"], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🥩", "name": "steak", "lastsFor": 5], 
                         ["defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🍬", "name": "extreme candy", "lastsFor": 365], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 1095, "name": "hot sauce", "emoji": "🌶"],
                         ["emoji": "🥫", "name": "xo sauce", "lastsFor": 30, "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["name": "shrimp", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🦐", "lastsFor": 3], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 8, "emoji": "🥬", "name": "parsley"], 
                         ["lastsFor": 14, "emoji": "🥓", "name": "sausage", "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "tomato", "emoji": "🍅", "lastsFor": 10], 
                         ["name": "tapioca pearls", "lastsFor": 365, "emoji": "⚫️", "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🌮", "lastsFor": 28, "name": "tortillas"], 
                         ["lastsFor": 1825, "name": "vanilla", "defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🍨"],
                         ["name": "fries", "emoji": "🍟", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 3], 
                         ["emoji": "🍄", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 10, "name": "mushroom"], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "radish", "emoji": "🥕", "lastsFor": 14], 
                         ["emoji": "🍊", "name": "oranges", "lastsFor": 10, "defaultSL": DefaultStorageLocation.pantry.rawValue], 
                         ["name": "potato", "lastsFor": 30, "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🥔"], 
                         ["emoji": "🍇", "lastsFor": 14, "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "blueberries"], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 6, "name": "blackberries", "emoji": "🍇"], 
                         ["lastsFor": 180, "name": "brandy", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🍺"], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "butter", "emoji": "🧈", "lastsFor": 120], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 10, "emoji": "🥕", "name": "beets"], 
                         ["name": "cider", "emoji": "🍺", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 365], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 14, "name": "cauliflower", "emoji": "🥦"], 
                         ["lastsFor": 2, "defaultSL": DefaultStorageLocation.refrigertator.rawValue, "emoji": "🐚", "name": "clam"], 
                         ["name": "cranberries", "lastsFor": 21, "emoji": "🍇", "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["name": "dressing", "lastsFor": 60, "emoji": "🥫", "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["lastsFor": 28, "defaultSL": DefaultStorageLocation.pantry.rawValue, "name": "doritos", "emoji": "🍟"], 
                         ["defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🍟", "lastsFor": 28, "name": "cheetos"], 
                         ["lastsFor": 28, "defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🍟", "name": "takis"], 
                         ["lastsFor": 30, "emoji": "🧃", "name": "juice", "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["name": "lettuce", "emoji": "🥬", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 14], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "mayonnaise", "lastsFor": 90, "emoji": "🥫"], 
                         ["emoji": "🧀", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "mozzarella", "lastsFor": 35], 
                         ["name": "macaroon", "emoji": "🍜", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 3], 
                         ["lastsFor": 60, "name": "mustard", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🥫"], 
                         ["lastsFor": 4, "emoji": "🍖", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "meatloaf"], 
                         ["emoji": "🍿", "name": "popcorn", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 60], 

                         ["name": "peaches", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 4, "emoji": "🍑"], 
                         ["emoji": "🥨", "defaultSL": DefaultStorageLocation.pantry.rawValue, "name": "pretzels", "lastsFor": 14], 
                         ["name": "popsicle", "emoji": "🧊", "lastsFor": 210, "defaultSL": DefaultStorageLocation.freezer.rawValue], 
                         ["emoji": "🍎", "name": "pomegranate", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 60], 
                         ["name": "quail egg", "emoji": "🥚", "lastsFor": 30, "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["emoji": "🍺", "defaultSL": DefaultStorageLocation.pantry.rawValue, "name": "rum", "lastsFor": 180], 
                         ["name": "raisins", "emoji": "🍇", "lastsFor": 180, "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["name": "ravioli", "emoji": "🥟", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 5], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 3, "name": "salmon", "emoji": "🐟"], 
                         ["emoji": "🥪", "name": "sandwich", "lastsFor": 3, "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🦃", "name": "turkey", "lastsFor": 5], 
                         ["name": "frosting", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🧁", "lastsFor": 90], 
                         ["emoji": "🍫", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "fudge", "lastsFor": 21], 
                         ["lastsFor": 365, "name": "flour", "defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🌾"], 
                         ["name": "gravy", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 4, "emoji": "🍲"], 
                         ["emoji": "🍊", "name": "grapefruit", "lastsFor": 180, "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["name": "ground beef", "defaultSL": DefaultStorageLocation.freezer.rawValue, "emoji": "🥩", "lastsFor": 120], 
                         ["name": "hazelnut", "lastsFor": 180, "emoji": "🌰", "defaultSL": DefaultStorageLocation.pantry.rawValue], 
                         ["name": "burgers", "defaultSL": DefaultStorageLocation.freezer.rawValue, "lastsFor": 150, "emoji": "🍔"], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 120, "name": "turnip", "emoji": "🍠"], 
                         ["name": "pasta", "emoji": "🍝", "lastsFor": 720, "defaultSL": DefaultStorageLocation.pantry.rawValue], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "breadfruit", "emoji": "🍐", "lastsFor": 4], 
                         ["name": "buckwheat", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 60, "emoji": "🌾"], 
                         ["lastsFor": 14, "name": "cucumber", "emoji": "🥒", "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["name": "lemons", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🍋", "lastsFor": 21], 
                         ["lastsFor": 2, "name": "red velvet cake", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🍰"], 
                         ["lastsFor": 7, "emoji": "🍋", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "star fruit"], 
                         ["name": "dragon fruit", "emoji": "🍎", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 14], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 180, "name": "peanut butter", "emoji": "🥜"], 
                         ["name": "oreo pie", "lastsFor": 3, "emoji": "🥧", "defaultSL": DefaultStorageLocation.refrigerator.rawValue], 
                         ["name": "cheese cake", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 5, "emoji": "🧀"], 
                         ["lastsFor": 4, "name": "brownies", "defaultSL": DefaultStorageLocation.pantry.rawValue, "emoji": "🍫"], 
                         ["emoji": "🥫", "lastsFor": 240, "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "sauce"], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "emoji": "🥒", "lastsFor": 545, "name": "pickles"], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "peas", "emoji": "🌰", "lastsFor": 6], 
                         ["name": "rice", "emoji": "🍚", "defaultSL": DefaultStorageLocation.pantry.rawValue, "lastsFor": 1460], 
                         ["lastsFor": 90, "defaultSL": DefaultStorageLocation.freezer.rawValue, "name": "chinese food", "emoji": "🇨🇳"], 
                         ["emoji": "🇯🇵", "defaultSL": DefaultStorageLocation.freezer.rawValue, "name": "japanese food", "lastsFor": 60], 
                         ["name": "chicken soup", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 4, "emoji": "🐣"], 
                         ["emoji": "🍜", "name": "chicken noodle soup", "defaultSL": DefaultStorageLocation.refrigerator.rawValue, "lastsFor": 4], 
                         ["lastsFor": 14, "name": "sweet potatoes", "emoji": "🍠", "defaultSL": DefaultStorageLocation.pantry.rawValue], 
                         ["defaultSL": DefaultStorageLocation.refrigerator.rawValue, "name": "grape", "emoji": "🍇", "lastsFor": 7],

                         ["name": "brussel sprouts", "emoji": "🥬", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999], ["emoji": "🥗", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "name": "corn salad", "lastsFor": 9999999], ["name": "dill", "emoji": "🥬", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "name": "lettuce", "emoji": "🥬", "lastsFor": 9999999], ["name": "sea beet", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "emoji": "🥬", "lastsFor": 9999999], ["lastsFor": 9999999, "defaultSL": DefaultStorageLocation.changeMe.rawValue, "name": "sea kale", "emoji": "🥬"], ["emoji": "🥬", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "name": "water grass", "lastsFor": 9999999], ["name": "wheatgrass", "emoji": "🌾", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999], ["emoji": "🍈", "name": "bittermelon", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999], ["name": "eggplant", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999, "emoji": "🍆"], ["name": "olive fruit", "emoji": "🍐", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999], ["name": "pumpkin", "emoji": "🎃", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "emoji": "🌶", "name": "sweet pepper", "lastsFor": 9999999], ["emoji": "🍈", "lastsFor": 9999999, "name": "winter melon", "defaultSL": DefaultStorageLocation.changeMe.rawValue], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "name": "chickpeas", "emoji": "🌰", "lastsFor": 9999999], ["lastsFor": 9999999, "name": "common peas", "emoji": "🌰", "defaultSL": DefaultStorageLocation.changeMe.rawValue], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999, "name": "indian pea", "emoji": "🌰"], ["lastsFor": 9999999, "name": "peanut", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "emoji": "🥜"], ["emoji": "🌰", "name": "soybean", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999], ["emoji": "🥬", "name": "chives", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999], ["name": "garlic chives", "emoji": "🥬", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999], ["name": "lemon grass", "lastsFor": 9999999, "emoji": "🥬", "defaultSL": DefaultStorageLocation.changeMe.rawValue], ["name": "leek", "emoji": "🥬", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999], ["lastsFor": 9999999, "emoji": "🥥", "name": "lotus root", "defaultSL": DefaultStorageLocation.changeMe.rawValue], ["lastsFor": 9999999, "name": "pearl onion", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "emoji": "🧅"], ["lastsFor": 9999999, "name": "spring onion", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "emoji": "🧅"], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999, "name": "green onion", "emoji": "🧅"], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999, "name": "mondrian wild rice", "emoji": "🍚"], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "emoji": "🎍", "lastsFor": 9999999, "name": "bamboo shoot"], ["name": "beetroot", "lastsFor": 9999999, "defaultSL": DefaultStorageLocation.changeMe.rawValue, "emoji": "🥕"], ["emoji": "🌼", "lastsFor": 9999999, "name": "canna", "defaultSL": DefaultStorageLocation.changeMe.rawValue], ["emoji": "🥕", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999, "name": "cassava"], ["name": "horseradish", "emoji": "🥕", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999], ["name": "parsnip", "emoji": "🥕", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "name": "tea", "emoji": "🍵", "lastsFor": 9999999], ["lastsFor": 9999999, "emoji": "🌰", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "name": "tigernut"], ["emoji": "🥬", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999, "name": "sea lettuce"], ["emoji": "🍪", "lastsFor": 9999999, "defaultSL": DefaultStorageLocation.changeMe.rawValue, "name": "biscuit"], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "name": "meat", "emoji": "🥩", "lastsFor": 9999999], ["emoji": "🍲", "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999, "name": "hot pot"], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999, "emoji": "🐖", "name": "pork chop"], ["lastsFor": 9999999, "name": "panna cotta", "emoji": "🍮", "defaultSL": DefaultStorageLocation.changeMe.rawValue], ["emoji": "🥞", "name": "pancake mix", "lastsFor": 9999999, "defaultSL": DefaultStorageLocation.changeMe.rawValue], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "name": "wontons", "emoji": "🥟", "lastsFor": 9999999], ["lastsFor": 9999999, "emoji": "🥟", "name": "frozen dumplings", "defaultSL": DefaultStorageLocation.changeMe.rawValue], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999, "name": "dumplings", "emoji": "🥟"], ["lastsFor": 9999999, "name": "sourdough", "emoji": "🌾", "defaultSL": DefaultStorageLocation.changeMe.rawValue], ["defaultSL": DefaultStorageLocation.changeMe.rawValue, "name": "sourdough bread", "emoji": "🍞", "lastsFor": 9999999],
]
//

//for item in newArrayOfFoods {
//    let data = ["name": item.key, "emoji": item.value, "defaultSL": DefaultStorageLocation.changeMe.rawValue, "lastsFor": 9999999] as [String : Any]
//    newerArrayOfFoods.append(data)
//}
//
//
//print(newerArrayOfFoods)
 
